-- M13. Пользователи, роли §5, токены обновления и журнал аудита.

create table app_user (
    id            bigint generated by default as identity primary key,
    username      varchar(32)  not null,
    password_hash varchar(100) not null,
    full_name     varchar(200) not null,
    enabled       boolean      not null default true,
    created_at    timestamptz  not null,
    version       bigint       not null default 0,
    constraint app_user_username_uk unique (username),
    constraint app_user_username_format check (username ~ '^[a-z0-9._-]{3,32}$')
);

create table app_user_role (
    user_id bigint      not null references app_user (id) on delete cascade,
    role    varchar(32) not null,
    primary key (user_id, role),
    constraint app_user_role_known check (role in (
        'RECEIVER', 'PICKER', 'DISPATCHER', 'SHIPPER', 'WAREHOUSE_ADMIN', 'ANALYST', 'SYSTEM_ADMIN'))
);

-- Хранится только SHA-256 токена: утечка таблицы не даёт действующих токенов.
create table refresh_token (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references app_user (id) on delete cascade,
    token_hash varchar(64) not null,
    issued_at  timestamptz not null,
    expires_at timestamptz not null,
    revoked_at timestamptz,
    constraint refresh_token_hash_uk unique (token_hash)
);

create index refresh_token_user_idx on refresh_token (user_id);

-- NFR-SEC-03: кто, что, когда, старое и новое значение. Движения остатков сюда не пишутся:
-- их журнал ведётся отдельно и сам по себе неизменяем.
create table audit_log (
    id          bigint generated by default as identity primary key,
    occurred_at timestamptz not null,
    actor       varchar(32) not null,
    action      varchar(64) not null,
    entity_type varchar(64) not null,
    entity_id   varchar(64),
    old_value   jsonb,
    new_value   jsonb
);

create index audit_log_entity_idx on audit_log (entity_type, entity_id, occurred_at);
create index audit_log_time_idx on audit_log (occurred_at);
