-- M1. Склад, зоны, ячейки; M15. Версии планировки.
-- Все расстояния и координаты в метрах, объёмы в м³, массы в кг.

create table warehouse (
    id                bigint generated by default as identity primary key,
    code              varchar(6)       not null,
    name              varchar(200)     not null,
    default_speed_mps double precision not null,
    -- Текущая версия планировки; 0 — планировка ещё не сохранялась.
    layout_version    bigint           not null default 0,
    created_at        timestamptz      not null,
    version           bigint           not null default 0,
    constraint warehouse_code_uk unique (code),
    constraint warehouse_code_format check (code ~ '^[A-Z][A-Z0-9]{0,5}$'),
    constraint warehouse_speed_positive check (default_speed_mps > 0)
);

-- Зона задаёт тип ячеек по умолчанию и политику хранения (FR-M6-02a, INV-08).
create table zone (
    id             bigint generated by default as identity primary key,
    warehouse_id   bigint       not null references warehouse (id),
    code           varchar(16)  not null,
    name           varchar(200) not null,
    type           varchar(16)  not null,
    storage_policy varchar(16)  not null,
    constraint zone_code_uk unique (warehouse_id, code),
    constraint zone_type_known check (type in ('PICKING', 'BULK', 'BUFFER', 'QUARANTINE', 'DEFECT')),
    constraint zone_policy_known check (storage_policy in ('DEDICATED', 'SHARED'))
);

-- Ячейки стеллажей выводятся из планировки (row_no и далее заполнены). Виртуальные места —
-- зона приёмки, зона отгрузки, тара сборщика — адреса на стеллаже не имеют.
create table location (
    id             bigint generated by default as identity primary key,
    warehouse_id   bigint           not null references warehouse (id),
    zone_id        bigint           references zone (id),
    code           varchar(32)      not null,
    type           varchar(16)      not null,
    row_no         integer,
    section_no     integer,
    level_no       integer,
    position_no    integer,
    -- Центр ячейки на плане и высота полки над полом (FR-M1-04, §8.1).
    x              double precision,
    y              double precision,
    z              double precision,
    -- Точка на лицевой линии ряда: от неё ячейка проецируется на ось прохода (§8.7, А1).
    access_x       double precision,
    access_y       double precision,
    facing         varchar(5),
    max_weight_kg  double precision,
    max_volume_m3  double precision,
    blocked        boolean          not null default false,
    block_reason   varchar(200),
    -- Ячейка исчезла из планировки, но строка остаётся: на неё ссылается история движений.
    active         boolean          not null default true,
    layout_version bigint,
    version        bigint           not null default 0,
    constraint location_code_uk unique (code),
    constraint location_type_known check (type in (
        'PICKING', 'BULK', 'BUFFER', 'QUARANTINE', 'DEFECT', 'RECEIVING', 'SHIPPING', 'CONTAINER')),
    constraint location_address_complete check (
        (row_no is null) = (section_no is null)
        and (row_no is null) = (level_no is null)
        and (row_no is null) = (position_no is null)),
    constraint location_block_has_reason check (not blocked or block_reason is not null),
    constraint location_capacity_positive check (
        (max_weight_kg is null or max_weight_kg > 0) and (max_volume_m3 is null or max_volume_m3 > 0))
);

create index location_row_idx on location (warehouse_id, row_no) where row_no is not null;
create index location_zone_idx on location (zone_id);

-- Документ планировки хранится целиком: он и есть источник геометрии (§7.15.1), ячейки
-- выводятся из него. Версии не удаляются, чтобы маршруты прошлых заданий оставались
-- воспроизводимыми (FR-M1-13, FR-M15-10).
create table layout_version (
    id           bigint generated by default as identity primary key,
    warehouse_id bigint      not null references warehouse (id),
    version      bigint      not null,
    document     jsonb       not null,
    created_by   varchar(32) not null,
    created_at   timestamptz not null,
    constraint layout_version_uk unique (warehouse_id, version)
);
