-- M2. Номенклатура: SKU и штрихкоды. Ограничение ячеек по классам хранения (FR-M1-06).

create table sku (
    id            bigint generated by default as identity primary key,
    article       varchar(64)      not null,
    name          varchar(300)     not null,
    uom           varchar(16)      not null,
    length_m      double precision not null,
    width_m       double precision not null,
    height_m      double precision not null,
    weight_kg     double precision not null,
    volume_m3     double precision not null,
    storage_class varchar(16)      not null,
    -- Заполняются расчётом по истории отборов (FR-M2-05); до первого расчёта пусты.
    abc_class     varchar(1),
    xyz_class     varchar(1),
    created_at    timestamptz      not null,
    version       bigint           not null default 0,
    constraint sku_article_uk unique (article),
    -- Артикул кодируется в QR как SKU:<артикул>, поэтому пробелы в нём недопустимы.
    constraint sku_article_token check (article ~ '^\S+$'),
    constraint sku_dimensions_positive check (length_m > 0 and width_m > 0 and height_m > 0 and volume_m3 > 0),
    constraint sku_weight_positive check (weight_kg > 0),
    constraint sku_storage_class_known check (storage_class in ('NORMAL', 'FRAGILE', 'HEAVY', 'OVERSIZED')),
    constraint sku_abc_known check (abc_class in ('A', 'B', 'C')),
    constraint sku_xyz_known check (xyz_class in ('X', 'Y', 'Z'))
);

create index sku_name_idx on sku (lower(name));

-- Штрихкод однозначно указывает на один SKU, иначе скан на приёмке неоднозначен (FR-M2-03).
create table sku_barcode (
    id      bigint generated by default as identity primary key,
    sku_id  bigint      not null references sku (id) on delete cascade,
    barcode varchar(64) not null,
    type    varchar(16) not null,
    constraint sku_barcode_uk unique (barcode),
    constraint sku_barcode_type_known check (type in ('EAN13', 'CODE128', 'INTERNAL'))
);

create index sku_barcode_sku_idx on sku_barcode (sku_id);

-- Список допустимых классов через запятую; пусто — ячейка принимает любой класс.
alter table location add column allowed_storage_classes varchar(64);
