-- M4. Остатки и журнал движений. Инварианты §11.2 держит сама СУБД (§12.2).

create table stock (
    id                bigint generated by default as identity primary key,
    location_id       bigint      not null references location (id),
    sku_id            bigint      not null references sku (id),
    quantity          integer     not null default 0,
    reserved_quantity integer     not null default 0,
    updated_at        timestamptz not null,
    version           bigint      not null default 0,
    constraint stock_location_sku_uk unique (location_id, sku_id),
    -- INV-01
    constraint stock_quantity_non_negative check (quantity >= 0 and reserved_quantity >= 0),
    -- INV-02: доступное количество quantity − reserved_quantity не бывает отрицательным (FR-M4-02)
    constraint stock_reserved_within_quantity check (reserved_quantity <= quantity)
);

create index stock_sku_idx on stock (sku_id) where quantity > 0;

-- FR-M4-03, FR-M4-04. Направление движения зависит от типа: приход только приходит, отгрузка
-- и списание только уходят, корректировка — ровно в одну сторону.
create table movement (
    id            bigint generated by default as identity primary key,
    type          varchar(16)  not null,
    sku_id        bigint       not null references sku (id),
    quantity      integer      not null,
    location_from bigint       references location (id),
    location_to   bigint       references location (id),
    document_type varchar(32),
    document_id   varchar(64),
    username      varchar(32)  not null,
    occurred_at   timestamptz  not null,
    comment       varchar(500),
    constraint movement_type_known check (type in (
        'RECEIPT', 'PUTAWAY', 'TRANSFER', 'PICK', 'SHIP', 'ADJUSTMENT', 'WRITE_OFF', 'RETURN')),
    constraint movement_quantity_positive check (quantity > 0),
    constraint movement_distinct_locations check (location_from is distinct from location_to),
    constraint movement_direction check (
        (type = 'RECEIPT' and location_from is null and location_to is not null)
        or (type in ('PUTAWAY', 'TRANSFER', 'PICK', 'RETURN') and location_from is not null and location_to is not null)
        or (type in ('SHIP', 'WRITE_OFF') and location_from is not null and location_to is null)
        or (type = 'ADJUSTMENT' and (location_from is null) <> (location_to is null)))
);

create index movement_sku_idx on movement (sku_id, occurred_at);
create index movement_from_idx on movement (location_from, occurred_at);
create index movement_to_idx on movement (location_to, occurred_at);

-- NFR-R-04: журнал только дополняется, ошибка исправляется новой записью. Триггер действует и
-- для владельца таблицы, в отличие от отзыва прав UPDATE/DELETE у прикладной роли.
create function movement_append_only() returns trigger
    language plpgsql as
$$
begin
    raise exception 'Журнал движений неизменяем: исправление вносится новой записью (NFR-R-04)'
        using errcode = 'restrict_violation';
end;
$$;

create trigger movement_append_only
    before update or delete on movement
    for each row execute function movement_append_only();
