-- M3. Приёмка: документ прихода с ожидаемыми позициями и фактом (FR-M3-01, FR-M3-02).

create sequence receipt_number_seq;

create table receipt (
    id           bigint generated by default as identity primary key,
    warehouse_id bigint       not null references warehouse (id),
    number       varchar(32)  not null,
    supplier     varchar(200) not null,
    status       varchar(16)  not null,
    created_by   varchar(32)  not null,
    created_at   timestamptz  not null,
    closed_at    timestamptz,
    version      bigint       not null default 0,
    constraint receipt_number_uk unique (number),
    constraint receipt_status_known check (status in ('EXPECTED', 'RECEIVING', 'CLOSED')),
    constraint receipt_closed_at check ((status = 'CLOSED') = (closed_at is not null))
);

-- Строка без ожидаемого количества (0) — товар, пришедший сверх документа: это тоже расхождение.
create table receipt_line (
    id                 bigint generated by default as identity primary key,
    receipt_id         bigint  not null references receipt (id) on delete cascade,
    sku_id             bigint  not null references sku (id),
    quantity_expected  integer not null,
    quantity_received  integer not null default 0,
    quantity_put_away  integer not null default 0,
    constraint receipt_line_sku_uk unique (receipt_id, sku_id),
    constraint receipt_line_quantities check (
        quantity_expected >= 0 and quantity_received >= 0
        and quantity_put_away >= 0 and quantity_put_away <= quantity_received)
);
