-- M5. Заказы на отгрузку и волны.

create sequence wave_number_seq;

create table wave (
    id           bigint generated by default as identity primary key,
    warehouse_id bigint      not null references warehouse (id),
    number       varchar(32) not null,
    status       varchar(16) not null,
    -- Критерии, по которым волна сформирована: для воспроизводимости и разбора (FR-M5-05).
    criteria     jsonb       not null,
    created_by   varchar(32) not null,
    created_at   timestamptz not null,
    version      bigint      not null default 0,
    constraint wave_number_uk unique (number),
    constraint wave_status_known check (status in ('FORMED', 'ALLOCATED', 'COMPLETED', 'CANCELLED'))
);

-- «order» — зарезервированное слово SQL, поэтому таблица называется customer_order.
create table customer_order (
    id           bigint generated by default as identity primary key,
    warehouse_id bigint       not null references warehouse (id),
    number       varchar(64)  not null,
    counterparty varchar(200) not null,
    -- 1 — самый низкий, 9 — самый высокий.
    priority     integer      not null,
    deadline_at  timestamptz,
    carrier      varchar(100),
    direction    varchar(100),
    -- Срочный заказ обрабатывается вне волны (FR-M5-08).
    hot          boolean      not null default false,
    status       varchar(20)  not null,
    wave_id      bigint       references wave (id),
    created_at   timestamptz  not null,
    version      bigint       not null default 0,
    constraint customer_order_number_uk unique (number),
    constraint customer_order_priority_range check (priority between 1 and 9),
    constraint customer_order_status_known check (status in (
        'NEW', 'ALLOCATED', 'PLANNED', 'IN_PROGRESS', 'PICKED', 'PARTIALLY_PICKED', 'PACKED', 'SHIPPED', 'CANCELLED')),
    constraint customer_order_hot_outside_wave check (not (hot and wave_id is not null))
);

create index customer_order_selection_idx on customer_order (warehouse_id, status, deadline_at);
create index customer_order_wave_idx on customer_order (wave_id);

create table order_line (
    id                 bigint generated by default as identity primary key,
    order_id           bigint  not null references customer_order (id) on delete cascade,
    line_no            integer not null,
    sku_id             bigint  not null references sku (id),
    quantity_ordered   integer not null,
    quantity_allocated integer not null default 0,
    quantity_picked    integer not null default 0,
    quantity_shipped   integer not null default 0,
    constraint order_line_no_uk unique (order_id, line_no),
    constraint order_line_ordered_positive check (quantity_ordered > 0),
    -- INV-06 и его продолжения: не резервируется, не отбирается и не отгружается больше заказанного.
    constraint order_line_quantities check (
        quantity_allocated between 0 and quantity_ordered
        and quantity_picked between 0 and quantity_ordered
        and quantity_shipped between 0 and quantity_picked)
);

create index order_line_sku_idx on order_line (sku_id);
