-- M6. Аллокация: какие ячейки и сколько закреплены за строкой заказа.
-- INV-03: сумма активных резервов по паре «место × SKU» равна stock.reserved_quantity.

create table allocation (
    id              bigint generated by default as identity primary key,
    order_line_id   bigint      not null references order_line (id),
    location_id     bigint      not null references location (id),
    sku_id          bigint      not null references sku (id),
    quantity        integer     not null,
    quantity_picked integer     not null default 0,
    status          varchar(16) not null,
    reserved_at     timestamptz not null,
    -- Срок жизни резерва (FR-M6-04); снимается, когда заказ входит в задание.
    expires_at      timestamptz,
    closed_at       timestamptz,
    version         bigint      not null default 0,
    constraint allocation_quantity_positive check (quantity > 0),
    constraint allocation_picked_within check (quantity_picked between 0 and quantity),
    constraint allocation_status_known check (status in ('RESERVED', 'PICKED', 'RELEASED', 'FAILED')),
    constraint allocation_closed_at check ((status = 'RESERVED') = (closed_at is null))
);

create index allocation_active_idx on allocation (location_id, sku_id) where status = 'RESERVED';
create index allocation_line_idx on allocation (order_line_id);
create index allocation_expiry_idx on allocation (expires_at) where status = 'RESERVED';
