-- M9. Тара, сборщики, батчи и задания на сборку.

-- Тара и тележки (FR-M13-04). У каждой тары своё виртуальное место: отобранное лежит в нём до
-- отгрузки (FR-M10-11), и сумма остатков таких мест равна отобранному, но не отгруженному (INV-09).
create table container (
    id            bigint generated by default as identity primary key,
    warehouse_id  bigint           not null references warehouse (id),
    code          varchar(32)      not null,
    type          varchar(16)      not null,
    max_volume_m3 double precision not null,
    max_weight_kg double precision not null,
    -- Число отделений тележки: столько заказов собирается за один проход (FR-M7-02).
    slots         integer          not null,
    location_id   bigint           not null references location (id),
    active        boolean          not null default true,
    version       bigint           not null default 0,
    constraint container_code_uk unique (code),
    constraint container_location_uk unique (location_id),
    constraint container_type_known check (type in ('TOTE', 'CART')),
    constraint container_capacity_positive check (max_volume_m3 > 0 and max_weight_kg > 0 and slots > 0)
);

-- Реестр сборщиков (FR-M9-01): статус и последняя подтверждённая ячейка.
create table worker (
    id                  bigint generated by default as identity primary key,
    warehouse_id        bigint       not null references warehouse (id),
    user_id             bigint       not null references app_user (id),
    code                varchar(32)  not null,
    -- PIN для входа с терминала вместе с бейджем (FR-M10-02); хранится хэшем.
    pin_hash            varchar(100) not null,
    status              varchar(16)  not null,
    current_location_id bigint       references location (id),
    version             bigint       not null default 0,
    constraint worker_user_uk unique (user_id),
    constraint worker_code_uk unique (code),
    constraint worker_status_known check (status in ('OFF_SHIFT', 'AVAILABLE', 'BUSY', 'BREAK'))
);

create sequence task_number_seq;

-- Батч: заказы, собираемые за один проход, и чем он построен (§8.3). Задание — батч,
-- назначаемый сборщику, с маршрутом в виде упорядоченных шагов.
create table batch (
    id                   bigint generated by default as identity primary key,
    warehouse_id         bigint           not null references warehouse (id),
    wave_id              bigint           references wave (id),
    container_id         bigint           not null references container (id),
    algorithm_batching   varchar(32)      not null,
    algorithm_routing    varchar(32)      not null,
    total_volume_m3      double precision not null,
    total_weight_kg      double precision not null,
    estimated_distance_m double precision,
    estimated_duration_s double precision,
    created_at           timestamptz      not null
);

-- Заказ в батче и его отделение тележки. Один заказ — в одном батче (FR-M7-03).
create table batch_order (
    batch_id bigint  not null references batch (id),
    order_id bigint  not null references customer_order (id),
    slot     integer not null,
    primary key (batch_id, order_id),
    constraint batch_order_order_uk unique (order_id),
    constraint batch_order_slot_uk unique (batch_id, slot),
    constraint batch_order_slot_positive check (slot > 0)
);

create table task (
    id                bigint generated by default as identity primary key,
    number            varchar(32) not null,
    warehouse_id      bigint      not null references warehouse (id),
    batch_id          bigint      not null references batch (id),
    worker_id         bigint      references worker (id),
    status            varchar(16) not null,
    priority          integer     not null,
    deadline_at       timestamptz,
    created_at        timestamptz not null,
    assigned_at       timestamptz,
    started_at        timestamptz,
    finished_at       timestamptz,
    actual_duration_s double precision,
    version           bigint      not null default 0,
    constraint task_number_uk unique (number),
    constraint task_batch_uk unique (batch_id),
    constraint task_status_known check (status in (
        'QUEUED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED')),
    constraint task_assigned_has_worker check (status not in ('ASSIGNED', 'IN_PROGRESS') or worker_id is not null)
);

create index task_queue_idx on task (warehouse_id, status, deadline_at);
create index task_worker_idx on task (worker_id) where status in ('ASSIGNED', 'IN_PROGRESS');

create table task_step (
    id                bigint generated by default as identity primary key,
    task_id           bigint      not null references task (id),
    sequence          integer     not null,
    location_id       bigint      not null references location (id),
    sku_id            bigint      not null references sku (id),
    order_line_id     bigint      not null references order_line (id),
    allocation_id     bigint      not null references allocation (id),
    quantity_required integer     not null,
    quantity_picked   integer     not null default 0,
    container_slot    integer     not null,
    status            varchar(16) not null,
    confirmed_at      timestamptz,
    exception_type    varchar(24),
    comment           varchar(500),
    -- INV-05: номер шага уникален в задании; непрерывность ряда обеспечивает построение задания.
    constraint task_step_sequence_uk unique (task_id, sequence),
    constraint task_step_quantities check (quantity_required > 0 and quantity_picked between 0 and quantity_required),
    constraint task_step_status_known check (status in ('PENDING', 'PICKED', 'SHORT', 'SKIPPED', 'CANCELLED')),
    constraint task_step_exception_known check (exception_type in (
        'INSUFFICIENT', 'MISSING', 'DAMAGED', 'LOCATION_UNAVAILABLE', 'MISPLACED'))
);

-- Резерв собирается одним живым шагом; шаги расформированного задания на него больше не претендуют.
create unique index task_step_allocation_uk on task_step (allocation_id) where status <> 'CANCELLED';
